### ISSUE TITLE
`GoToDoor` environment display looks a little jagged in the terminal

### ISSUE THREAD

**Issue by Sid-Bhatia-0** [JuliaReinforcementLearning/GridWorlds.jl#11]
`GoToDoor` environment display looks a little jagged on the terminal.

![Screenshot from 2020-10-03 12-58-47](https://user-images.githubusercontent.com/32610387/94986289-23858000-057b-11eb-8ee1-4ae1027a252b.png)

Could we use a different character than the current door emoji? Something like a wall but a different color perhaps?

Keeping constant pixel dimensions for all characters would probably lead to a more uniform visual representation in the terminal.

**Comment by findmyway** [comment]
Yes, it is also not shown correctly on Windows.

![image](https://user-images.githubusercontent.com/5612003/94994962-90c20100-05cd-11eb-8487-ef994d3d1a12.png)


I'll look for another symbol.

**Comment by Sid-Bhatia-0** [comment]
Needs to be reopened. Just a reminder :)

```
julia> versioninfo()
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = /usr/bin/vim

julia> 
```

![Screenshot from 2020-10-05 16-07-39](https://user-images.githubusercontent.com/32610387/95069918-fd034880-0724-11eb-9bdb-88de91c04f66.png)

**Comment by findmyway** [comment]
I tried on the Ubuntu and it is shown correctly:

![image](https://user-images.githubusercontent.com/5612003/95071990-1a441100-073d-11eb-8709-1a23f84aaa1d.png)

Try the solution here?

https://unix.stackexchange.com/a/97694

**Comment by Sid-Bhatia-0** [comment]
Hmm... Tried a few of these. Still doesn't seem to work for me.

I also tried setting UTF-8 manually in the terminal tab in the menubar. 

![Screenshot from 2020-10-06 09-27-57](https://user-images.githubusercontent.com/32610387/95157393-83b43600-07b6-11eb-87fb-85a3fca717fc.png)

This solution [https://stackoverflow.com/a/12650490](https://stackoverflow.com/a/12650490) mentions the files `/etc/rc.conf` and `/etc/locale.conf` which don't seem to exist for me. Any ideas?

**Comment by Sid-Bhatia-0** [comment]
Closing this issue since it works with my current system running Manjaro Linux
```
julia> versioninfo()
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```
