### ISSUE TITLE
CollectGems env needs a rng argument for reproducibility

### ISSUE THREAD

**Issue by Sid-Bhatia-0** [JuliaReinforcementLearning/GridWorlds.jl#44]

**Comment by RajGhugare19** [comment]
@Sid-Bhatia-0 Is anyone doing this? If only the rng param has to be passed to the constructor I could wrap it up by tonight(IST)

**Comment by Sid-Bhatia-0** [comment]
I was going to do this later. It'd be nice if you can get this done by tonight.

So go ahead @RajGhugare19 . Thanks!
