### ISSUE TITLE
Fix Travis CI

### ISSUE THREAD

**Issue by findmyway** [JuliaReinforcementLearning/GridWorlds.jl#47]
I think lazily loading Makie.jl should be enough to fix this issue.

**Comment by sriyash421** [comment]
https://github.com/JuliaReinforcementLearning/GridWorlds.jl/blob/ff940a038ccb7e49464fa52ac949e45c1d4d5f91/src/GridWorlds.jl#L16

Here I see the part is commented. Just using this will work?

**Comment by findmyway** [comment]
Yes I think so. I'll test it later tonight.
