### ISSUE TITLE
DynamicObstacles updates obstacles only on MOVE_FORWARD action

### ISSUE THREAD

**Issue by Sid-Bhatia-0** [JuliaReinforcementLearning/GridWorlds.jl#53]
The obstacles in `DynamicObstacles` seem to only get updated on taking the `MOVE_FORWARD` action and not on the `TURN_LEFT` or `TURN_RIGHT` actions.

I was wondering if this is by design. After all, `TURN_LEFT` and `TURN_RIGHT` do consume a time-step, just like `MOVE_FORWARD`. So it seems more natural to me that the agent should be vigilant of the obstacles for each step it takes.

**Comment by RajGhugare19** [comment]
Yes, this was done by design. I agree with you. I will change this :) Thank you
