### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by Sid-Bhatia-0** [JuliaReinforcementLearning/GridWorlds.jl#64]
Tracking this here instead of README to ensure our implementations do not have significant performance issues.

**Comment by sriyash421** [comment]
```
env = Env()
    t = @benchmark for i=1:num_resets reset!(env) end
    push!(reset_times, mean(t).time/1e9)

    t = @benchmark for i=1:num_frames _ = get_state(env); env(RIGHT) end
    push!(frame_per_sec, num_frames/(mean(t).time*1e9))
```

Executed the above. But it throws env not found strangely

**Comment by sriyash421** [comment]
@Sid-Bhatia-0 @findmyway

**Comment by findmyway** [comment]
Maybe the scoping issue. You'd better wrap it in a function to do testing

**Comment by Sid-Bhatia-0** [comment]
Added benchmarks #126 #127
