### ISSUE TITLE
Purpose of GoToDoor is not novel

### ISSUE THREAD

**Issue by Sid-Bhatia-0** [JuliaReinforcementLearning/GridWorlds.jl#66]
GoToDoor does not seem to serve a purpose in terms of demonstrating something unique.
From the perspective of implementing the RLBase API for it, the purpose of this environment seems vague.

1. There is no goal to reach in this environment. `get_reward` and `get_terminal` become subjective here.
2. There is no point in having a door without a key if one can just walk through it just like one walks through the narrow empty entrance between rooms, as given in `FourRooms`.
3. If we are going to consider adding a key, then well, we already have `DoorKey` to demonstrate this concept.

I suggest we either come up with some tangible and useful purpose for it, or better, remove the `GoToDoor` environment altogether.

**Comment by sriyash421** [comment]
@Sid-Bhatia-0 The GoToDoor in the original package was used for natural language tasks. It has a string like "Go to red door" etc.

**Comment by Sid-Bhatia-0** [comment]
Oh, okay.

So, is there a simple way to write the RLBase API for this environment (especially the methods `get_terminal` and `get_reward`) ?

How do we (if at all at this stage) incorporate natural langauge tasks? By the way, forgive my ignorance. I have not worked in NLP before.

**Comment by Sid-Bhatia-0** [comment]
One of the things that could be done for now is to have a target field in the environment struct. Then on reaching the target door we get a reward and terminate. Else on reaching any other coloured door, we receive negative reward and terminate.

This is still novel in the sense of having multiple possible endpoints out of which one is the correct target. This is also similar to the goal of the natural languate task except for the natural lanugage part of it.

Does this sound reasonable?

**Comment by sriyash421** [comment]
Yes it does seem reasonable. That is how exactly the env is build.on a basic level. A random door is chosen in the env and assigned as the target. And the reward is given if done is called outside the gate. Else negative if anywhere else.

 For the natural language task the env itself generated a string using the target doot say "go to the red door" and it is included in the observation space during training. That is mostly handled by the algorithms and not the environment. We just need to make sure to add a mission field in the env struct.

**Comment by Sid-Bhatia-0** [comment]
Thank you for the explanation @sriyash421 

So for now, we just need a target field that will also be output by the `get_state` method along with the regular observation. And later we can add a "target to natural language mission converter".

**Comment by Sid-Bhatia-0** [comment]
Fixed in #68
