### ISSUE TITLE
Add sokoban

### ISSUE THREAD

**Issue by findmyway** [JuliaReinforcementLearning/GridWorlds.jl#77]
- https://github.com/deepmind/boxoban-levels
- https://github.com/mpSchrader/gym-sokoban

Ideally, this environment should be integrated in https://github.com/JuliaReinforcementLearning/Maze.jl

**Comment by Sid-Bhatia-0** [comment]
Fixed in #112

**Comment by findmyway** [comment]
Nice, could you also add a GIF in readme?

**Comment by Sid-Bhatia-0** [comment]
Yes. I forgot to do it earlier. Will add it soon in a PR along with some general documentation.
